<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5b4c2769ccce93a80ec99f0bf3e12247
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Braintree\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Braintree\\' => 
        array (
            0 => __DIR__ . '/..' . '/braintree/braintree_php/lib/Braintree',
        ),
    );

    public static $prefixesPsr0 = array (
        'B' => 
        array (
            'Braintree' => 
            array (
                0 => __DIR__ . '/..' . '/braintree/braintree_php/lib',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5b4c2769ccce93a80ec99f0bf3e12247::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5b4c2769ccce93a80ec99f0bf3e12247::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit5b4c2769ccce93a80ec99f0bf3e12247::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
